[project]
name = "realsense-mediapipe-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyrealsense2>=2.56.5.9235",
]

[project.scripts]
realsense-mediapipe-tracking = "realsense_mediapipe_tracking:main"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
